// Runtime configuration loader
// In production, this reads from window.__APP_CONFIG__ (generated by docker-entrypoint.sh)
// In development, it falls back to Vite environment variables

interface AppConfig {
  API_BASE_URL: string;
}

declare global {
  interface Window {
    __APP_CONFIG__?: AppConfig;
  }
}

export function getConfig(): AppConfig {
  // Production: use runtime config from window
  if (window.__APP_CONFIG__) {
    return window.__APP_CONFIG__;
  }

  // Development: use Vite env variables
  return {
    API_BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000',
  };
}

export const config = getConfig();
